# flask-pod-with-secret-volume.yaml
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-with-secret-volume
  labels:
    app: flask-with-secret-volume
spec:
  containers:
  - name: flask-with-secret
    image: quay.io/iamgini/my-flask-app:1.0
    volumeMounts:
    - name: mysecret-volume
      mountPath: '/etc/password-mounted-path'
      readOnly: true  # Establecer readOnly en true para prevenir escritura
  volumes:
  - name: mysecret-volume
    secret:
      secretName: my-second-secret  # El nombre del Secret va aquí