# flask-pod-with-secret.yaml
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-with-secret
  labels:
    app: flask-with-secret
spec:
  containers:
  - name: flask-with-secret
    image: quay.io/iamgini/my-flask-app:1.0
    env:
    - name: PASSWORD_ENV_VAR  # Nombre de la variable de entorno
      valueFrom:
        secretKeyRef:
          name: my-first-secret  # Nombre del objeto secret
          key: db_password       # Nombre de la clave en el objeto secret