apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-12-23T16:40:32Z"
  labels:
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "23"
  uid: f9277a31-f71a-4905-9c23-76db44a93ea8
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
